name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "$EC2_SSH_KEY" > ec2_ssh_key.pem
        chmod 600 ec2_ssh_key.pem
        scp -i ec2_ssh_key.pem -o StrictHostKeyChecking=no -r ./* $EC2_USERNAME@$EC2_HOST:~/app
        ssh -i ec2_ssh_key.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST '
          cd ~/app
          npm install
          pm2 restart app || pm2 start app.js --name app
        '
        rm -f ec2_ssh_key.pem